version: "2"

services:
  postgres:
    image: postgres:13.2
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: opensanctions
      POSTGRES_PASSWORD: opensanctions

  worker:
    build: .
    command: opensanctions crawl all
    links:
      - postgres
    volumes:
      - "./data/data:/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
    environment:
      OPENSANCTIONS_DATABASE_URI: postgresql://opensanctions:opensanctions@postgres/opensanctions
